### ISSUE TITLE
Ubuntu16?

### ISSUE THREAD

**Issue by xuwuzhou** [jypjypjypjyp/lvio_fusion#2]

**Comment by xuwuzhou** [comment]
Can I run this on Ubuntu16?

**Comment by jypjypjypjyp** [comment]
> Can I run this on Ubuntu16?

Yes, Ubuntu 16 is also supported.

**Comment by xuwuzhou** [comment]
Hi, jyp @jypjypjypjyp . Have you met the similar problem?

catkin_make error:

CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘fmt::v7::format_error::format_error(char const*)’中：
/usr/local/include/fmt/format.h:750：对‘vtable for fmt::v7::format_error’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘fmt::v7::detail::throw_format_error(char const*)’中：
/usr/local/include/fmt/format.h:811：对‘fmt::v7::format_error::~format_error()’未定义的引用
/usr/local/include/fmt/format.h:811：对‘typeinfo for fmt::v7::format_error’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘std::make_unsigned<long>::type fmt::v7::detail::to_unsigned<long>(long)’中：
/usr/local/include/fmt/core.h:407：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘std::make_unsigned<int>::type fmt::v7::detail::to_unsigned<int>(int)’中：
/usr/local/include/fmt/core.h:407：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘void fmt::v7::print<Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >(fmt::v7::basic_format_string<char, fmt::v7::type_identity<Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >::type>, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> >&&)’中：
/usr/local/include/fmt/core.h:2979：对‘fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::appender, char> >)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘void fmt::v7::print<>(fmt::v7::basic_format_string<char>)’中：
/usr/local/include/fmt/core.h:2979：对‘fmt::v7::vprint(fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::appender, char> >)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler>::on_error(char const*)’中：
/usr/local/include/fmt/core.h:691：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘char const* fmt::v7::detail::do_parse_arg_id<char, char const* fmt::v7::detail::parse_replacement_field<char, fmt::v7::detail::format_string_checker<char, fmt::v7::detail::error_handler, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >&>(char const*, char const*, fmt::v7::detail::format_string_checker<char, fmt::v7::detail::error_handler, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >&)::id_adapter&>(char const*, char const*, fmt::v7::detail::format_string_checker<char, fmt::v7::detail::error_handler, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >&)’中：
/usr/local/include/fmt/core.h:2177：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘void fmt::v7::detail::check_string_type_spec<char, fmt::v7::detail::error_handler&>(char, fmt::v7::detail::error_handler&)’中：
/usr/local/include/fmt/core.h:2593：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘int fmt::v7::detail::parse_nonnegative_int<char>(char const*&, char const*, int)’中：
/usr/local/include/fmt/core.h:2109：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘void fmt::v7::detail::format_value<char, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > >(fmt::v7::detail::buffer<char>&, Eigen::Transpose<Eigen::Matrix<double, 4, 1, 0, 4, 1> > const&, fmt::v7::detail::locale_ref)’中：
/usr/local/include/fmt/ostream.h:114：对‘std::locale fmt::v7::detail::locale_ref::get<std::locale>() const’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘char const* fmt::v7::detail::parse_align<char, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&>(char const*, char const*, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&)’中：
/usr/local/include/fmt/core.h:2133：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘char const* fmt::v7::detail::parse_width<char, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&>(char const*, char const*, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&)’中：
/usr/local/include/fmt/core.h:2230：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘int fmt::v7::detail::get_dynamic_spec<fmt::v7::detail::width_checker, fmt::v7::basic_format_arg<fmt::v7::basic_format_context<fmt::v7::appender, char> >, fmt::v7::detail::error_handler>(fmt::v7::basic_format_arg<fmt::v7::basic_format_context<fmt::v7::appender, char> >, fmt::v7::detail::error_handler)’中：
/usr/local/include/fmt/format.h:2056：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘int fmt::v7::detail::get_dynamic_spec<fmt::v7::detail::precision_checker, fmt::v7::basic_format_arg<fmt::v7::basic_format_context<fmt::v7::appender, char> >, fmt::v7::detail::error_handler>(fmt::v7::basic_format_arg<fmt::v7::basic_format_context<fmt::v7::appender, char> >, fmt::v7::detail::error_handler)’中：
/usr/local/include/fmt/format.h:2056：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘char const* fmt::v7::detail::do_parse_arg_id<char, char const* fmt::v7::detail::parse_width<char, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&>(char const*, char const*, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&)::width_adapter&>(char const*, char const*, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&)’中：
/usr/local/include/fmt/core.h:2177：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘char const* fmt::v7::detail::do_parse_arg_id<char, char const* fmt::v7::detail::parse_precision<char, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&>(char const*, char const*, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&)::precision_adapter&>(char const*, char const*, fmt::v7::detail::specs_checker<fmt::v7::detail::dynamic_specs_handler<fmt::v7::basic_format_parse_context<char, fmt::v7::detail::error_handler> > >&)’中：
/usr/local/include/fmt/core.h:2177：对‘fmt::v7::detail::assert_fail(char const*, int, char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘fmt::v7::appender fmt::v7::detail::write_padded<(fmt::v7::align::type)1, fmt::v7::appender, char, fmt::v7::appender fmt::v7::detail::write<char, fmt::v7::appender>(fmt::v7::appender, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_specs<char> const&)::{lambda(fmt::v7::appender)#1}>(fmt::v7::appender, fmt::v7::basic_format_specs<char> const&, unsigned long, unsigned long, fmt::v7::appender fmt::v7::detail::write<char, fmt::v7::appender>(fmt::v7::appender, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_specs<char> const&)::{lambda(fmt::v7::appender)#1}&&)’中：
/usr/local/include/fmt/format.h:1284：对‘fmt::v7::detail::basic_data<void>::left_padding_shifts’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘unsigned long long fmt::v7::detail::width_checker<fmt::v7::detail::error_handler>::operator()<int, 0>(int)’中：
/usr/local/include/fmt/format.h:2018：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘unsigned long long fmt::v7::detail::width_checker<fmt::v7::detail::error_handler>::operator()<unsigned int, 0>(unsigned int)’中：
/usr/local/include/fmt/format.h:2018：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘unsigned long long fmt::v7::detail::width_checker<fmt::v7::detail::error_handler>::operator()<long long, 0>(long long)’中：
/usr/local/include/fmt/format.h:2018：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘unsigned long long fmt::v7::detail::width_checker<fmt::v7::detail::error_handler>::operator()<unsigned long long, 0>(unsigned long long)’中：
/usr/local/include/fmt/format.h:2018：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘unsigned long long fmt::v7::detail::width_checker<fmt::v7::detail::error_handler>::operator()<__int128, 0>(__int128)’中：
/usr/local/include/fmt/format.h:2018：对‘fmt::v7::detail::error_handler::on_error(char const*)’未定义的引用
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o:/usr/local/include/fmt/format.h:2018: 跟着更多未定义的参考到 fmt::v7::detail::error_handler::on_error(char const*)
collect2: error: ld returned 1 exit status
lvio_fusion/src/lvio_fusion_node/src/CMakeFiles/lvio_fusion_node.dir/build.make:641: recipe for target '/home/xuwuzhou/catkin_lvio_fusion/devel/lib/lvio_fusion_node/lvio_fusion_node' failed
make[2]: *** [/home/xuwuzhou/catkin_lvio_fusion/devel/lib/lvio_fusion_node/lvio_fusion_node] Error 1
CMakeFiles/Makefile2:3617: recipe for target 'lvio_fusion/src/lvio_fusion_node/src/CMakeFiles/lvio_fusion_node.dir/all' failed
make[1]: *** [lvio_fusion/src/lvio_fusion_node/src/CMakeFiles/lvio_fusion_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by jypjypjypjyp** [comment]
@xuwuzhou 没有遇到过，可能是环境的问题。

**Comment by xuwuzhou** [comment]
你好，我已经重新装了系统，从头配置了
PCL1.8
ROS kinetic
eigen 3.3.7
ceres 1.14
opencv 2
libgeographic-dev


但是，仍然报同样的错误：

/usr/bin/ld: warning: libpcl_common.so.1.8, needed by /home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so, may conflict with libpcl_common.so.1.7
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘sync_process()’中：
/home/xuwuzhou/catkin_lvio_fusion/src/lvio_fusion/src/lvio_fusion_node/src/lvio_fusion_node.cpp:163：对‘lvio_fusion::Estimator::InputImage(double, cv::Mat&, cv::Mat&, Sophus::SE3Group<double, 0>)’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘fmt::v8::detail::basic_data<void>::left_padding_shifts’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘std::locale fmt::v8::detail::locale_ref::get<std::locale>() const’未定义的引用

我怀疑可能是pcl版本的原因，我虽然从源码安装了pcl1.8，但是为了使用pcl_conversion,使用命令行安装了pcl_conversion,但是pcl_conversion是依赖于pcl1.7的，不知道同学你的pcl版本是多少。

**Comment by xuwuzhou** [comment]
完整的错误日志:

xuwuzhou@xuwuzhou-Lenovo-Rescuer-15ISK:~/catkin_lvio_fusion$ catkin_make 
Base path: /home/xuwuzhou/catkin_lvio_fusion
Source space: /home/xuwuzhou/catkin_lvio_fusion/src
Build space: /home/xuwuzhou/catkin_lvio_fusion/build
Devel space: /home/xuwuzhou/catkin_lvio_fusion/devel
Install space: /home/xuwuzhou/catkin_lvio_fusion/install
####
#### Running command: "make cmake_check_build_system" in "/home/xuwuzhou/catkin_lvio_fusion/build"
####
####
#### Running command: "make -j8 -l8" in "/home/xuwuzhou/catkin_lvio_fusion/build"
####
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target _lvio_fusion_node_generate_messages_check_deps_Step
[  0%] Built target _lvio_fusion_node_generate_messages_check_deps_CreateEnv
[  0%] Built target _lvio_fusion_node_generate_messages_check_deps_Init
[  0%] Built target _lvio_fusion_node_generate_messages_check_deps_UpdateWeights
[ 46%] Built target lvio_fusion
[ 54%] Built target lvio_fusion_node_generate_messages_cpp
[ 56%] Linking CXX executable /home/xuwuzhou/catkin_lvio_fusion/devel/lib/lvio_fusion_node/lvio_fusion_node
[ 66%] Built target lvio_fusion_node_generate_messages_lisp
[ 72%] Built target lvio_fusion_node_generate_messages_nodejs
[ 82%] Built target lvio_fusion_node_generate_messages_eus
[ 92%] Built target lvio_fusion_node_generate_messages_py
[ 92%] Built target lvio_fusion_node_generate_messages
/usr/bin/ld: warning: libpcl_common.so.1.8, needed by /home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so, may conflict with libpcl_common.so.1.7
CMakeFiles/lvio_fusion_node.dir/lvio_fusion_node.cpp.o：在函数‘sync_process()’中：
/home/xuwuzhou/catkin_lvio_fusion/src/lvio_fusion/src/lvio_fusion_node/src/lvio_fusion_node.cpp:163：对‘lvio_fusion::Estimator::InputImage(double, cv::Mat&, cv::Mat&, Sophus::SE3Group<double, 0>)’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘fmt::v8::detail::basic_data<void>::left_padding_shifts’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘std::locale fmt::v8::detail::locale_ref::get<std::locale>() const’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘fmt::v8::format_error::~format_error()’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘vtable for fmt::v8::format_error’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘fmt::v8::detail::assert_fail(char const*, int, char const*)’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘fmt::v8::detail::error_handler::on_error(char const*)’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘typeinfo for fmt::v8::format_error’未定义的引用
/home/xuwuzhou/catkin_lvio_fusion/devel/lib/liblvio_fusion.so：对‘fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)’未定义的引用
collect2: error: ld returned 1 exit status
lvio_fusion/src/lvio_fusion_node/src/CMakeFiles/lvio_fusion_node.dir/build.make:609: recipe for target '/home/xuwuzhou/catkin_lvio_fusion/devel/lib/lvio_fusion_node/lvio_fusion_node' failed
make[2]: *** [/home/xuwuzhou/catkin_lvio_fusion/devel/lib/lvio_fusion_node/lvio_fusion_node] Error 1
CMakeFiles/Makefile2:3146: recipe for target 'lvio_fusion/src/lvio_fusion_node/src/CMakeFiles/lvio_fusion_node.dir/all' failed
make[1]: *** [lvio_fusion/src/lvio_fusion_node/src/CMakeFiles/lvio_fusion_node.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by xuwuzhou** [comment]
整了三天，终于跑通了，给其他人提个醒，安装Sophus的时候，不要安装有fmt的那个版本，用git checkout 切换到没有fmt的最新版本

**Comment by jypjypjypjyp** [comment]
@xuwuzhou 谢谢提醒

**Comment by narutojxl** [comment]
Hi @xuwuzhou,  请教仁兄， 不带fmt的branch有多个，能请教下，具体是切换到哪个branch？

**Comment by xuwuzhou** [comment]
@narutojxl 不好意思，刚看到，sophus下载下来用git checkout 43028da1b2b9dbd9426c5eba779b7b3bc277ea4c 即可
