### ISSUE TITLE
KITTI LIDAR

### ISSUE THREAD

**Issue by xuwuzhou** [jypjypjypjyp/lvio_fusion#3]
KITTI数据集的雷达不能使用吗，为什么我把配置文件里的雷达选项打开，程序就跑不通？
[lvio_fusion_node-2] process has died [pid 7247, exit code -11, cmd /home/xuwuzhou/catkin_lvio_fusion/devel/lib/lvio_fusion_node/lvio_fusion_node __name:=lvio_fusion_node __log:=/home/xuwuzhou/.ros/log/04058954-d592-11eb-a2c5-ac2b6e9fe601/lvio_fusion_node-2.log].
log file: /home/xuwuzhou/.ros/log/04058954-d592-11eb-a2c5-ac2b6e9fe601/lvio_fusion_node-2*.log

**Comment by jypjypjypjyp** [comment]
你可以先用1.0的分支，后面代码重构了，依然在修改

**Comment by xuwuzhou** [comment]
Ok,我去试试，谢啦

**Comment by jypjypjypjyp** [comment]
![image](https://user-images.githubusercontent.com/34328687/123399378-20359700-d5d7-11eb-8cc7-308354991e70.png)
我刚才运行了一下，没有报错（效果上还有问题）。

**Comment by xuwuzhou** [comment]
这个是运行的是最新的主分支吗

**Comment by jypjypjypjyp** [comment]
是的

**Comment by xuwuzhou** [comment]
不应该啊，我再试试，有一种不详的预感，pcl1.7和pcl1.8可能有冲突的地方

**Comment by jypjypjypjyp** [comment]
我只测试过pcl1.8

**Comment by jypjypjypjyp** [comment]
我之测试过pcl1.8、pcl1.10

**Comment by xuwuzhou** [comment]
pcl1.8的pcl_conversion缺失问题你是怎么解决的呢，直接sudo apt-get install ros-XX-pcl-conversion吗

**Comment by jypjypjypjyp** [comment]
应该是的

**Comment by xuwuzhou** [comment]
还是在报错，只要不加入激光信息就没有问题，一旦加入激光信息，直接第一帧就开始出现段错误，定位出现的位置是:
seg.segment(*inliers, coefficients);(association.cpp的262行)，可能是因为生成bag的姿势不对？
我用的直接就是kitti2bag

**Comment by jypjypjypjyp** [comment]
SegmentGround是额外的优化，如果实在运行不了，可以注释

**Comment by xuwuzhou** [comment]
Ok,我试试

**Comment by xuwuzhou** [comment]
现在是能跑通了，不过出现了另一个问题就是轨迹明显不对(地图虽然是对的)
![2021-06-28 10-37-34屏幕截图](https://user-images.githubusercontent.com/44218507/123571617-30c75680-d7fd-11eb-8364-7057319d8f0e.png)

**Comment by xuwuzhou** [comment]
小车离地图很远，并且轨迹不知道在哪儿，看不到，感觉这个地面分段函数注释后的影响不小

**Comment by jypjypjypjyp** [comment]
可以输出轨迹吗？（/lvio_fusion_node/path）

**Comment by jypjypjypjyp** [comment]
可以在改为Release,ceres优化在Debug下很慢。 set(CMAKE_BUILD_TYPE Release)

**Comment by xuwuzhou** [comment]
好的，我试试，谢啦

**Comment by xuwuzhou** [comment]
在1.0的版本中仍然没有轨迹，不知道为什么，但是我刚刚看到上午更新了一个版本，在那个版本的基础上注释掉SegmentGround，可以输出比较好的轨迹
![image](https://user-images.githubusercontent.com/44218507/123589243-8579ca00-d81b-11eb-918c-c42c5278004e.png)

这个segmentground出错的问题，同学你有遇到吗，如果没有的话，可能是我这里pcl版本的原因问题

**Comment by jypjypjypjyp** [comment]
没有遇到过，我这里一直都是好的

**Comment by xuwuzhou** [comment]
Ok, 那这个issue我先关了，估计可能是pcl版本的问题

**Comment by xuwuzhou** [comment]
segmentground的问题解决了，原因是ubuntu16的底层编码和pcl1.8有冲突，也就是说ubuntu16最好不要用pcl1.8，直接1.7就可以
