### ISSUE TITLE
is it possible to use monocular camera?

### ISSUE THREAD

**Issue by CanCanZeng** [jypjypjypjyp/lvio_fusion#4]
Hi, thank you for sharing this project! Is it possible to use monocular camera?

**Comment by jypjypjypjyp** [comment]
@CanCanZeng Unfortunately, it doesn't support monocular camera.

**Comment by CanCanZeng** [comment]
OK, thank you for your reply.
Will you keep improving this repo to make it support monocular camera?

**Comment by jypjypjypjyp** [comment]
I don't have a plan to make it support monocular camera.

**Comment by CanCanZeng** [comment]
OK，thank you for your help!
