### ISSUE TITLE
Segmented graph optimization

### ISSUE THREAD

**Issue by wongkenchiang97** [jypjypjypjyp/lvio_fusion#7]
Hi, thanks for sharing a creative work. 

you said rotation and forward direction errors are mainly optimized.

Could you give me some advise on these?

1.How do the forward direction and rotation errors are mainly optimized particularly?

2.Do you have more information about the "optimization by different parts"?

thanks a lot

**Comment by jypjypjypjyp** [comment]
Thank you for your attention to my work. 

In the current work, the way to distinguish the two errors is by different optimization blocks. For example, the optimization block for the straight part only includes the forward direction. 

For the second point, I think that global pose graph optimization (especially for the loop closure constraints) is a kind of smoothing, but the errors are not uniformly generated. So I divide a whole trajectory into multiple parts. First, do a part-wise optimization through loop closure constraints, and then perform a frame-wise optimization inside each part.

**Comment by jypjypjypjyp** [comment]
@wongkenchiang97 
You can understand it as optimizing the part-wise error first and optimizing the frame-wise error second.

**Comment by wongkenchiang97** [comment]
I have to understand more on the optimization library so I can work with the part-wise and frame-wise optimization you have mentioned above.

@jypjypjypjyp Thanks a lot for your reply and the advises!!
