### ISSUE TITLE
Problem with Visual-Lidar on KAIST datasets

### ISSUE THREAD

**Issue by hellovuong** [jypjypjypjyp/lvio_fusion#8]
Hi, Thank you for your fantastic project.
I built the project successfully and tested the with Visual-Only, Visual-IMU, everything looks fine and the result is normal. However, when I tried to run on Visual-Lidar or Visual-IMU-Lidar the following errors have shown up:
`[pcl::SampleConsensusModel::getSamples] Can not select 0 unique points out of 0!
[pcl::RandomSampleConsensus::computeModel] No samples could be selected!
[pcl::SACSegmentation::segment] Error segmenting the model! No solution found.`
No point from lidar appears in the Visualization window.
I have checked the name of the topic when publishing the dataset, it is correct and has data. 
The version of PCL that I am using is 1.8 (ROS-Melodic) and also testing on pcl 1.10 (ROS Noetic), the same error appeared. 
Hope that can receive support from you!
Thanks,

**Comment by jypjypjypjyp** [comment]
Thank you for your attention. The lidar in the KAIST dataset isn't set horizontally. This project only adapts to horizontal lidars. In the experiment, only the Visual+IMU+GPS is used.

**Comment by hellovuong** [comment]
Thanks for the clarification.
